In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
school_layout = pd.read_csv('all_states_data.csv', encoding='latin')

In [3]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F'],
      dtype='object')

In [4]:
school_layout.head()

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,SCH_ENR_HI_M,SCH_ENR_HI_F,SCH_ENR_AM_M,SCH_ENR_AM_F,SCH_ENR_AS_M,...,TOT_DISCWODIS_EXPWE_M,TOT_DISCWODIS_EXPWE_F,TOT_DISCWODIS_EXPWOE_M,TOT_DISCWODIS_EXPWOE_F,TOT_DISCWDIS_EXPWOE_IDEA_M,TOT_DISCWDIS_EXPWE_IDEA_M,TOT_DISCWDIS_EXPWE_IDEA_F,TOT_DISCWDIS_EXPWOE_IDEA_F,TOT_DISCWDIS_EXPZT_IDEA_M,TOT_DISCWDIS_EXPZT_IDEA_F
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,5,0,0,0,0,...,-9,-9,0,0,-9,-9,-9,-9,-9,-9
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,0,0,0,0,0,...,-9,-9,0,0,-9,-9,-9,-9,-9,-9
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,0,0,14,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,2,0,0,0,0,...,-9,-9,0,0,-9,-9,-9,-9,-9,-9
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,140,143,2,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
#These columns are used for reporting harrassment and bullying
#school_layout = school_layout.drop(columns=['TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_DIS_M',
#                           'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F'])

In [6]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F'],
      dtype='object')

### Convert all the columns with values -9 to 0.

In [7]:
school_layout.replace(-9,0, inplace=True)
school_layout.replace('-9',0, inplace=True)
school_layout.replace(-10,0, inplace=True)
school_layout.replace(-20,0, inplace=True)
school_layout.replace(-5, 0, inplace=True)

In [8]:
school_layout['SCH_ENR_AS'] = school_layout['SCH_ENR_AS_F']+school_layout['SCH_ENR_AS_M']
school_layout['SCH_ENR_BL'] = school_layout['SCH_ENR_BL_M']+school_layout['SCH_ENR_BL_F']
school_layout['SCH_ENR_HP'] = school_layout['SCH_ENR_HP_M']+school_layout['SCH_ENR_HP_F']
school_layout['SCH_ENR_WH'] = school_layout['SCH_ENR_WH_M']+school_layout['SCH_ENR_WH_F']
school_layout['SCH_ENR_TR'] = school_layout['SCH_ENR_TR_M']+school_layout['SCH_ENR_TR_F']
school_layout['SCH_ENR_HI'] = school_layout['SCH_ENR_HI_M']+school_layout['SCH_ENR_HI_F']
school_layout['SCH_ENR_AM'] = school_layout['SCH_ENR_AM_M']+school_layout['SCH_ENR_AM_F']

In [9]:
display(school_layout['SCH_ENR_HP'].head())

0    2
1    0
2    0
3    0
4    0
Name: SCH_ENR_HP, dtype: int64

In [12]:
# school_layout = school_layout.drop(columns=['SCH_ENR_HI_M','SCH_ENR_HI_F','SCH_ENR_AM_M','SCH_ENR_AM_F','SCH_ENR_AS_M','SCH_ENR_AS_F',
#                             'SCH_ENR_BL_M','SCH_ENR_BL_F','SCH_ENR_TR_M','SCH_ENR_TR_F','SCH_ENR_HP_M','SCH_ENR_HP_F',
#                             'SCH_ENR_WH_M','SCH_ENR_WH_F'])

In [13]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'SCH_ENR_AS',
       'SCH_ENR_BL', 'SCH_ENR_HP', 'SCH_ENR_WH', 'SCH_ENR_TR', 'SCH_ENR_HI',
       'SCH_ENR_AM'],
      dtype='object')

### Create the following new fields. 
1. Total Enrollment (TOT_ENR) = Enrollment including male and female students.
2. Create a new field called Average Enrollment (AVG_ENR) = Total Enrollment/7 (because there are 7 races).  
3. Total SATACT = total number of TOT_SATACT_M + TOT_SATACT_F
4. VAL_SAT = TOT_SATACT/TOT_ENR

In [14]:
school_layout['TOT_ENR'] = school_layout['TOT_ENR_M'] + school_layout['TOT_ENR_F']

In [15]:
school_layout['AVG_ENR'] = school_layout['TOT_ENR']/7
school_layout['TOT_SATACT'] = school_layout['TOT_SATACT_M'] + school_layout['TOT_SATACT_F']
school_layout['VAL_SAT'] = school_layout['TOT_SATACT']/school_layout['TOT_ENR']

In [16]:
school_layout['VAL_WH'] = (school_layout['SCH_ENR_WH'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_BL'] = (school_layout['SCH_ENR_BL'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_HP'] = (school_layout['SCH_ENR_HP'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_TR'] = (school_layout['SCH_ENR_TR'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_HI'] = (school_layout['SCH_ENR_HI'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_AS'] = (school_layout['SCH_ENR_AS'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_AM'] = (school_layout['SCH_ENR_AM'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']

### Calculate score based on the VAL where
1. 0.0-0.2 = 5 
2. 0.2-0.4 = 4
3. 0.4-0.6 = 3
4. 0.6-0.8 = 2
5. 0.8-1.0 = 1 

## TODO: 
1. change the scoring to be better reflective of the percentages

In [17]:
school_layout['VAL_RACE'] = (school_layout['VAL_WH']+school_layout['VAL_BL']+\
    school_layout['VAL_HP']+school_layout['VAL_TR']+school_layout['VAL_HI']+\
    school_layout['VAL_AS']+school_layout['VAL_AM'])/7

In [18]:
def score(school_layout):
    val = school_layout['VAL_RACE']
    if val>0 and val<=0.2:
        return 5
    elif val>0.2 and val<=0.4:
        return 4
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 2
    else:
        return 1

def score3(school_layout):
    val = school_layout['VAL_GENDER']
    if val>0 and val<=0.2:
        return 5
    elif val>0.2 and val<=0.4:
        return 4
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 2
    else:
        return 1
    
def score5(school_layout):
    val = school_layout['VAL_OFFENSES']
    if val>0 and val<=0.2:
        return 5
    elif val>0.2 and val<=0.4:
        return 4
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 2
    else:
        return 1

In [19]:
def score2(school_layout):
    val = school_layout['VAL_AP_COURSES']
    if val>0 and val<=0.2:
        return 1
    elif val>0.2 and val<=0.4:
        return 2
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 4
    else:
        return 5

def score4(school_layout):
    val = school_layout['VAL_SATACT_COURSES']
    if val>0 and val<=0.2:
        return 1
    elif val>0.2 and val<=0.4:
        return 2
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 4
    else:
        return 5

In [20]:
school_layout['RACE_SCORE'] = school_layout.apply(score, axis=1)

In [21]:
display(school_layout['RACE_SCORE'].unique())

array([5, 4, 1], dtype=int64)

In [22]:
school_layout.head()

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,SCH_ENR_HI_M,SCH_ENR_HI_F,SCH_ENR_AM_M,SCH_ENR_AM_F,SCH_ENR_AS_M,...,VAL_SAT,VAL_WH,VAL_BL,VAL_HP,VAL_TR,VAL_HI,VAL_AS,VAL_AM,VAL_RACE,RACE_SCORE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,5,0,0,0,0,...,0.078125,0.247768,0.411830,0.127232,0.142857,0.103795,0.142857,0.142857,0.188457,5
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,0,0,0,0,0,...,0.076923,0.126374,0.587912,0.142857,0.142857,0.142857,0.142857,0.142857,0.204082,4
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,0,0,14,0,0,...,0.014317,0.212870,0.467275,0.142857,0.124135,0.142857,0.142857,0.127439,0.194327,5
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,2,0,0,0,0,...,0.105263,0.225564,0.304511,0.142857,0.011278,0.090226,0.142857,0.142857,0.151450,5
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,140,143,2,0,0,...,0.000000,0.395495,0.120130,0.142857,0.111607,0.259131,0.140016,0.140016,0.187036,5

In [23]:
school_layout['VAL_GENDER']=(school_layout['TOT_ENR_M'] - school_layout['TOT_ENR_F']).abs()/school_layout['TOT_ENR']
school_layout['GENDER_SCORE'] = school_layout.apply(score3, axis=1)

In [24]:
school_layout['VAL_AP_COURSES'] = (school_layout['TOT_APENR_M'] + school_layout['TOT_APENR_F'])/school_layout['TOT_ENR']
school_layout['AP_SCORE'] = school_layout.apply(score2, axis=1)
school_layout['VAL_SATACT_COURSES'] = (school_layout['TOT_SATACT_M'] + school_layout['TOT_SATACT_F'])/school_layout['TOT_ENR']
school_layout['SATACT_SCORE'] = school_layout.apply(score4, axis=1)
school_layout['COURSES_SCORE'] = (school_layout['AP_SCORE']+school_layout['AP_SCORE'])//2

In [25]:
school_layout['TOT_ARR'] = (school_layout['TOT_DISCWODIS_ARR_M'] + school_layout['TOT_DISCWODIS_ARR_F'])
school_layout['TOT_EXP'] = school_layout['TOT_DISCWODIS_EXPWE_M'] + school_layout['TOT_DISCWODIS_EXPWE_F'] +school_layout['TOT_DISCWODIS_EXPWOE_M'] + school_layout['TOT_DISCWODIS_EXPWOE_F']
school_layout['TOT_HARR'] = school_layout['TOT_HBDISCIPLINED_SEX_M'] + school_layout['TOT_HBDISCIPLINED_SEX_F'] + school_layout['TOT_HBDISCIPLINED_RAC_M'] + school_layout['TOT_HBDISCIPLINED_RAC_F']+ school_layout['TOT_HBDISCIPLINED_DIS_M'] + school_layout['TOT_HBDISCIPLINED_DIS_F']
school_layout['TOT_SUSP'] = school_layout['TOT_DISCWODIS_ISS_M'] + school_layout['TOT_DISCWODIS_ISS_F']
school_layout['VAL_OFFENSES'] = (school_layout['TOT_ARR']*0.4 + school_layout['TOT_EXP']*0.2 + school_layout['TOT_SUSP']*0.1  + school_layout['TOT_HARR']*0.3)
school_layout['OFFENSES_SCORE'] = school_layout.apply(score5, axis=1)

In [26]:
school_layout['SCHOOL_SCORE'] = (school_layout['RACE_SCORE'] + school_layout['GENDER_SCORE'] + school_layout['COURSES_SCORE']
    + school_layout['OFFENSES_SCORE'])

In [27]:
display(school_layout.head())

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,SCH_ENR_HI_M,SCH_ENR_HI_F,SCH_ENR_AM_M,SCH_ENR_AM_F,SCH_ENR_AS_M,...,VAL_SATACT_COURSES,SATACT_SCORE,COURSES_SCORE,TOT_ARR,TOT_EXP,TOT_HARR,TOT_SUSP,VAL_OFFENSES,OFFENSES_SCORE,SCHOOL_SCORE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,5,0,0,0,0,...,0.078125,1,5,0,0,0,0,0.0,1,12
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,0,0,0,0,0,...,0.076923,1,5,0,0,0,0,0.0,1,11
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,0,0,14,0,0,...,0.014317,1,5,0,0,6,0,1.8,1,12
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,2,0,0,0,0,...,0.105263,1,5,0,0,0,0,0.0,1,12
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,140,143,2,0,0,...,0.000000,5,5,0,0,0,115,11.5,1,16

In [28]:
display(school_layout['COURSES_SCORE'].unique())
display(school_layout['RACE_SCORE'].unique())
display(school_layout['OFFENSES_SCORE'].unique())
display(school_layout['GENDER_SCORE'].unique())

array([5, 1, 2, 3, 4], dtype=int64)

array([5, 4, 1], dtype=int64)

array([1, 2, 4, 5, 3], dtype=int64)

array([1, 5, 4, 3, 2], dtype=int64)

In [29]:
school_layout['SCHOOL_SCORE'].unique()

array([12, 11, 16, 17, 15, 13, 18, 19, 20, 14,  8, 10,  9,  7],
      dtype=int64)

In [30]:
school_layout.fillna(0)

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,SCH_ENR_HI_M,SCH_ENR_HI_F,SCH_ENR_AM_M,SCH_ENR_AM_F,SCH_ENR_AS_M,...,VAL_SATACT_COURSES,SATACT_SCORE,COURSES_SCORE,TOT_ARR,TOT_EXP,TOT_HARR,TOT_SUSP,VAL_OFFENSES,OFFENSES_SCORE,SCHOOL_SCORE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,5,0,0,0,0,...,0.078125,1,5,0,0,0,0,0.0,1,12
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,0,0,0,0,0,...,0.076923,1,5,0,0,0,0,0.0,1,11
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,0,0,14,0,0,...,0.014317,1,5,0,0,6,0,1.8,1,12
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,2,0,0,0,0,...,0.105263,1,5,0,0,0,0,0.0,1,12
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,140,143,2,0,0,...,0.000000,5,5,0,0,0,115,11.5,1,16
5,5,ALABAMA,AL,Albertville City,Albertville High Sch,260,221,2,2,5,...,0.234749,2,1,2,0,0,6,1.4,1,12
6,6,ALABAMA,AL,Albertville City,Evans Elem Sch,161,173,2,2,2,...,0.000000,5,5,0,0,2,2,0.8,2,17
7,7,ALABAMA,AL,Albertville City,Albertville Elem Sch,218,215,0,2,2,...,0.000000,5,5,0,0,0,0,0.0,1,16
8,8,ALABAMA,AL,Albertville City,Big Spring Lake Kinderg Sch,134,128,2,0,2,...,0.000000,5,5,0,0,0,0,0.0,1,16
9,9,ALABAMA,AL,Albertville City,Albertville Primary Sch,281,269,2,2,2,...,0.000000,5,5,0,0,0,0,0.0,1,16
10,10,ALABAMA,AL,Marshall County,Kate Duncan Smith DAR Middle,8,5,2,2,0,...,0.000000,5,5,0,29,0,24,8.2,1,15
11,11,ALABAMA,AL,Marshall County,Asbury Sch,92,95,2,0,2,...,0.224490,2,1,2,33,2,86,16.6,1,12
12,12,ALABAMA,AL,Marshall County,Claysville Jr High Sch,8,8,0,2,2,...,0.000000,5,5,0,6,0,2,1.4,1,16
13,13,ALABAMA,AL,Marshall County,Douglas Elem Sch,95,83,0,0,0,...,0.000000,5,5,0,13,2,12,4.4,1,15
14,14,ALABAMA,AL,Marshall County,Douglas High Sch,77,65,2,2,2,...,0.476431,3,2,4,36,6,174,28.0,1,13
15,15,ALABAMA,AL,Marshall County,Brindlee Mountain Elementary School,11,8,2,0,0,...,0.000000,5,5,0,0,0,15,1.5,1,15
16,16,ALABAMA,AL,Marshall County,Kate D Smith DAR High Sch,2,2,0,0,0,...,0.505447,3,2,0,47,0,73,16.7,1,12
17,17,ALABAMA,AL,Marshall County,Brindlee Mountain Primary School,5,5,2,0,0,...,0.000000,5,5,0,2,0,0,0.4,4,18
18,18,ALABAMA,AL,Marshall County,Robert D Sloman Primary,104,89,2,2,2,...,0.000000,5,5,0,7,0,0,1.4,1,16
19,19,ALABAMA,AL,Marshall County,Brindlee Mt Middle Sch,11,5,0,0,2,...,0.000000,5,5,0,27,0,51,10.5,1,15
20,20,ALABAMA,AL,Marshall County,Brindlee Mt High Sch,11,8,0,0,2,...,0.473829,3,1,2,5,0,80,9.8,1,11
21,21,ALABAMA,AL,Marshall County,Kate D Smith DAR Elem Sch,2,2,2,2,0,...,0.000000,5,5,0,2,0,2,0.6,2,16
22,22,ALABAMA,AL,Marshall County,Douglas Middle Sch,89,71,2,2,0,...,0.000000,5,5,0,66,0,94,22.6,1,16
23,23,ALABAMA,AL,Marshall County,Asbury Elem Sch,98,101,0,2,0,...,0.000000,5,5,0,0,0,4,0.4,4,19
24,24,ALABAMA,AL,Hoover City,Trace Crossings Elem Sch,116,56,0,0,17,...,0.000000,5,5,0,0,0,2,0.2,5,20
25,25,ALABAMA,AL,Hoover City,Greystone Elem Sch,20,20,0,0,23,...,0.000000,5,5,0,0,0,2,0.2,5,20
26,26,ALABAMA,AL,Hoover City,Hoover High Sch,113,116,0,2,80,...,0.416245,3,1,0,0,2,2,0.8,2,13
27,27,ALABAMA,AL,Hoover City,Berry Middle Sch,35,44,0,2,35,...,0.000000,5,5,0,0,0,2,0.2,5,20
28,28,ALABAMA,AL,Hoover City,South Shades Crest Elem Sch,29,20,0,0,14,...,0.000000,5,5,0,0,0,0,0.0,1,16
29,29,ALABAMA,AL,Hoover City,Robert F Bumpus Middle Sch,35,29,0,2,32,...,0.000000,5,5,0,0,2,4,1.0,1,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96330,96330,WYOMING,WY,Sweetwater County School District #2,Washington Elementary,23,17,0,0,0,...,0.000000,5,5,0,0,0,4,0.4,4,19
96331,96331,WYOMING,WY,Sweetwater County School District #2,Lincoln Middle School,38,41,5,2,2,...,0.000000,5,5,0,0,2,56,6.2,1,16
96332,96332,WYOMING,WY,Sweetwater County School District #2,Jackson Elementary,23,29,0,2,0,...,0.000000,5,5,0,0,0,0,0.0,1,16
96333,96333,WYOMING,WY,Sweetwater County School District #2,Truman Elementary,20,20,2,2,0,...,0.000000,5,5,0,0,0,2,0.2,5,20
96334,96334,WYOMING,WY,Sweetwater County School District #2,Harrison Elementary,8,11,0,0,0,...,0.000000,5,5,0,0,0,8,0.8,2,16
96335,96335,WYOMING,WY,Sweetwater County School District #2,Thoman Ranch Elementary,0,2,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,11
96336,96336,WYOMING,WY,Washakie County School District #2,Ten Sleep K-12,0,0,0,0,2,...,0.145455,1,1,0,0,0,2,0.2,5,15
96337,96337,WYOMING,WY,Teton County School District #1,Colter Elementary,113,119,0,0,8,...,0.000000,5,5,0,0,0,6,0.6,2,17
96338,96338,WYOMING,WY,Teton County School District #1,Jackson Elementary,119,128,0,2,8,...,0.000000,5,5,0,0,0,4,0.4,4,19
96339,96339,WYOMING,WY,Teton County School District #1,Jackson Hole High School,95,89,2,2,5,...,0.000000,5,2,0,0,0,35,3.5,1,13
96340,96340,WYOMING,WY,Teton County School District #1,Jackson Hole Middle School,92,92,0,2,2,...,0.000000,5,5,0,0,0,19,1.9,1,16
96341,96341,WYOMING,WY,Teton County School District #1,Alta Elementary,0,0,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,15
96342,96342,WYOMING,WY,Teton County School District #1,Kelly Elementary,0,0,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,15
96343,96343,WYOMING,WY,Teton County School District #1,Moran Elementary,2,2,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,11
96344,96344,WYOMING,WY,Teton County School District #1,Wilson Elementary,2,8,0,0,2,...,0.000000,5,5,0,0,0,0,0.0,1,15
96345,96345,WYOMING,WY,Teton County School District #1,Summit High School,20,8,2,2,0,...,0.000000,5,5,0,0,0,12,1.2,1,15
96346,96346,WYOMING,WY,Weston County School District #7,Upton Middle School,0,0,0,2,0,...,0.000000,5,5,0,2,0,7,1.1,1,15
96347,96347,WYOMING,WY,Weston County School District #7,Upton Elementary,0,0,2,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,15
96348,96348,WYOMING,WY,Weston County School District #7,Upton High School,0,0,0,2,0,...,0.240000,2,1,0,0,0,4,0.4,4,14
96349,96349,WYOMING,WY,Washakie County School District #1,Worland High School,53,38,2,0,2,...,0.272500,2,1,0,0,0,52,5.2,1,12
96350,96350,WYOMING,WY,Washakie County School District #1,Worland Middle School,41,44,0,0,0,...,0.000000,5,5,0,0,0,20,2.0,1,16
96351,96351,WYOMING,WY,Washakie County School District #1,East Side Elementary,17,23,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,16
96352,96352,WYOMING,WY,Washakie County School District #1,South Side Elementary,26,20,2,0,2,...,0.000000,5,5,0,0,0,0,0.0,1,16
96353,96353,WYOMING,WY,Washakie County School District #1,West Side Elementary,35,41,2,2,0,...,0.000000,5,5,0,0,0,2,0.2,5,20
96354,96354,WYOMING,WY,Northeast Wyoming BOCES,Powder River Basin Children's Center,0,2,2,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,14
96355,96355,WYOMING,WY,Region V BOCES,C-Bar-V Ranch,5,2,8,0,2,...,0.140000,1,5,0,0,19,0,5.7,1,13
96356,96356,WYOMING,WY,Wyoming Department of Family Services,Wyoming Girls School,0,8,0,11,0,...,0.000000,5,5,0,0,0,0,0.0,1,12
96357,96357,WYOMING,WY,Wyoming Department of Family Services,Wyoming Boys School,23,0,11,0,0,...,0.117647,1,5,0,0,0,0,0.0,1,12
96358,96358,WYOMING,WY,Youth Emergency Services Inc. - Administration...,Youth Emergency Services Inc.,2,2,0,2,2,...,0.307692,2,5,0,0,0,7,0.7,2,17
96359,96359,WYOMING,WY,Saint Stephen's Indian School Admin Office,Saint Stephen's Indian School,0,0,110,107,0,...,0.142857,1,5,0,0,7,67,8.8,1,15

In [31]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'SCH_ENR_AS',
       'SCH_ENR_BL', 'SCH_ENR_HP', 'SCH_ENR_WH', 'SCH_ENR_TR', 'SCH_ENR_HI',
       'SCH_ENR_AM', 'TOT_ENR', 'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH',
       'VAL_BL', 'VAL_HP', 'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE',
       'RACE_SCORE', 'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES',
       'AP_SCORE', 'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE',
       'TOT_ARR', 'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES',
       'OFFENSES_SCORE', 'SCHOOL_SCORE'],
      dtype='object')

In [32]:
print(school_layout.index)
print(school_layout['LEA_STATE'].unique())

RangeIndex(start=0, stop=96360, step=1)
['AL' 'AK' 'AZ' 'AR' 'CA' 'CO' 'CT' 'DE' 'DC' 'FL' 'GA' 'HI' 'ID' 'IL'
 'IN' 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MA' 'MI' 'MN' 'MS' 'MO' 'MT' 'NE'
 'NV' 'NH' 'NJ' 'NM' 'NY' 'NC' 'ND' 'OH' 'OK' 'OR' 'PA' 'RI' 'SC' 'SD'
 'TN' 'TX' 'UT' 'VT' 'VA' 'WA' 'WV' 'WI' 'WY']

Choose same number of schools from each of the states.

In [33]:
states = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', \
 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', \
 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', \
 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
school_layout_new = pd.DataFrame()
for state in states:
    df = school_layout.loc[school_layout['LEA_STATE']==state]
    df = df[:100]
    school_layout_new = school_layout_new.append(df, ignore_index=True)

```
import random
school_layout_small = school_layout.sample(n=600)
display(school_layout_small['LEA_STATE'].unique())
```

In [34]:
school_layout_new['LEA_STATE'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [35]:
school_layout_new['ABLE_MALE']=school_layout_new['TOT_DISCWODIS_EXPWE_M']+school_layout_new['TOT_DISCWODIS_EXPWOE_M']
school_layout_new['ABLE_FEMALE']=school_layout_new['TOT_DISCWODIS_EXPWE_F']+school_layout_new['TOT_DISCWODIS_EXPWOE_F']
school_layout_new['DISABLE_MALE']=school_layout_new['TOT_DISCWDIS_EXPWE_IDEA_M']+school_layout_new['TOT_DISCWDIS_EXPWOE_IDEA_M']
school_layout_new['DISABLE_FEMALE']=school_layout_new['TOT_DISCWDIS_EXPWE_IDEA_F']+school_layout_new['TOT_DISCWDIS_EXPWOE_IDEA_F']

In [36]:
school_layout_new

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,SCH_ENR_HI_M,SCH_ENR_HI_F,SCH_ENR_AM_M,SCH_ENR_AM_F,SCH_ENR_AS_M,...,TOT_EXP,TOT_HARR,TOT_SUSP,VAL_OFFENSES,OFFENSES_SCORE,SCHOOL_SCORE,ABLE_MALE,ABLE_FEMALE,DISABLE_MALE,DISABLE_FEMALE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,5,0,0,0,0,...,0,0,0,0.0,1,12,0,0,0,0
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,0,0,0,0,0,...,0,0,0,0.0,1,11,0,0,0,0
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,0,0,14,0,0,...,0,6,0,1.8,1,12,0,0,0,0
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,2,0,0,0,0,...,0,0,0,0.0,1,12,0,0,0,0
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,140,143,2,0,0,...,0,0,115,11.5,1,16,0,0,0,0
5,5,ALABAMA,AL,Albertville City,Albertville High Sch,260,221,2,2,5,...,0,0,6,1.4,1,12,0,0,0,0
6,6,ALABAMA,AL,Albertville City,Evans Elem Sch,161,173,2,2,2,...,0,2,2,0.8,2,17,0,0,0,0
7,7,ALABAMA,AL,Albertville City,Albertville Elem Sch,218,215,0,2,2,...,0,0,0,0.0,1,16,0,0,0,0
8,8,ALABAMA,AL,Albertville City,Big Spring Lake Kinderg Sch,134,128,2,0,2,...,0,0,0,0.0,1,16,0,0,0,0
9,9,ALABAMA,AL,Albertville City,Albertville Primary Sch,281,269,2,2,2,...,0,0,0,0.0,1,16,0,0,0,0
10,10,ALABAMA,AL,Marshall County,Kate Duncan Smith DAR Middle,8,5,2,2,0,...,29,0,24,8.2,1,15,20,9,13,2
11,11,ALABAMA,AL,Marshall County,Asbury Sch,92,95,2,0,2,...,33,2,86,16.6,1,12,24,9,6,0
12,12,ALABAMA,AL,Marshall County,Claysville Jr High Sch,8,8,0,2,2,...,6,0,2,1.4,1,16,4,2,2,2
13,13,ALABAMA,AL,Marshall County,Douglas Elem Sch,95,83,0,0,0,...,13,2,12,4.4,1,15,13,0,2,0
14,14,ALABAMA,AL,Marshall County,Douglas High Sch,77,65,2,2,2,...,36,6,174,28.0,1,13,34,2,2,0
15,15,ALABAMA,AL,Marshall County,Brindlee Mountain Elementary School,11,8,2,0,0,...,0,0,15,1.5,1,15,0,0,8,0
16,16,ALABAMA,AL,Marshall County,Kate D Smith DAR High Sch,2,2,0,0,0,...,47,0,73,16.7,1,12,34,13,4,2
17,17,ALABAMA,AL,Marshall County,Brindlee Mountain Primary School,5,5,2,0,0,...,2,0,0,0.4,4,18,2,0,0,0
18,18,ALABAMA,AL,Marshall County,Robert D Sloman Primary,104,89,2,2,2,...,7,0,0,1.4,1,16,7,0,2,0
19,19,ALABAMA,AL,Marshall County,Brindlee Mt Middle Sch,11,5,0,0,2,...,27,0,51,10.5,1,15,20,7,0,0
20,20,ALABAMA,AL,Marshall County,Brindlee Mt High Sch,11,8,0,0,2,...,5,0,80,9.8,1,11,5,0,2,0
21,21,ALABAMA,AL,Marshall County,Kate D Smith DAR Elem Sch,2,2,2,2,0,...,2,0,2,0.6,2,16,2,0,2,0
22,22,ALABAMA,AL,Marshall County,Douglas Middle Sch,89,71,2,2,0,...,66,0,94,22.6,1,16,53,13,17,2
23,23,ALABAMA,AL,Marshall County,Asbury Elem Sch,98,101,0,2,0,...,0,0,4,0.4,4,19,0,0,0,0
24,24,ALABAMA,AL,Hoover City,Trace Crossings Elem Sch,116,56,0,0,17,...,0,0,2,0.2,5,20,0,0,0,0
25,25,ALABAMA,AL,Hoover City,Greystone Elem Sch,20,20,0,0,23,...,0,0,2,0.2,5,20,0,0,0,0
26,26,ALABAMA,AL,Hoover City,Hoover High Sch,113,116,0,2,80,...,0,2,2,0.8,2,13,0,0,0,0
27,27,ALABAMA,AL,Hoover City,Berry Middle Sch,35,44,0,2,35,...,0,0,2,0.2,5,20,0,0,0,0
28,28,ALABAMA,AL,Hoover City,South Shades Crest Elem Sch,29,20,0,0,14,...,0,0,0,0.0,1,16,0,0,0,0
29,29,ALABAMA,AL,Hoover City,Robert F Bumpus Middle Sch,35,29,0,2,32,...,0,2,4,1.0,1,12,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5070,96065,WYOMING,WY,Carbon County School District #2,HEM Junior/Senior High School,2,5,0,2,2,...,0,0,13,1.3,1,16,0,0,0,0
5071,96066,WYOMING,WY,Carbon County School District #2,Encampment K-12 School,2,0,0,2,2,...,0,0,5,0.5,3,17,0,0,0,0
5072,96067,WYOMING,WY,Carbon County School District #2,Saratoga Middle/High School,8,5,5,2,0,...,0,2,15,2.1,1,16,0,0,0,0
5073,96068,WYOMING,WY,Laramie County School District #1,Central High School,74,86,8,5,5,...,2,0,8,1.2,1,13,2,0,0,0
5074,96069,WYOMING,WY,Laramie County School District #1,East High School,137,116,8,5,11,...,4,0,0,0.8,2,14,2,2,0,0
5075,96070,WYOMING,WY,Laramie County School District #1,Triumph High School,14,14,0,2,0,...,0,0,0,0.0,1,16,0,0,0,0
5076,96071,WYOMING,WY,Laramie County School District #1,Carey Junior High School,89,80,5,5,2,...,2,4,8,2.4,1,16,2,0,0,0
5077,96072,WYOMING,WY,Laramie County School District #1,Johnson Junior High School,122,110,8,5,8,...,0,4,14,2.6,1,16,0,0,0,0
5078,96073,WYOMING,WY,Laramie County School District #1,McCormick Junior High School,38,41,2,2,5,...,0,2,12,1.8,1,16,0,0,0,0
5079,96074,WYOMING,WY,Laramie County School District #1,Alta Vista Elementary,41,32,2,2,2,...,0,2,0,0.6,3,18,0,0,0,0
5080,96075,WYOMING,WY,Laramie County School District #1,Arp Elementary,62,62,2,2,2,...,0,4,0,1.2,1,16,0,0,0,0
5081,96076,WYOMING,WY,Laramie County School District #1,Baggs Elementary,35,41,2,5,0,...,0,0,0,0.0,1,16,0,0,0,0
5082,96077,WYOMING,WY,Laramie County School District #1,Bain Elementary,41,41,0,0,0,...,0,0,0,0.0,1,16,0,0,0,0
5083,96078,WYOMING,WY,Laramie County School District #1,Buffalo Ridge Elementary,26,29,0,2,2,...,0,0,4,0.4,4,19,0,0,0,0
5084,96079,WYOMING,WY,Laramie County School District #1,Cole Elementary,59,41,0,0,0,...,0,0,0,0.0,1,16,0,0,0,0
5085,96080,WYOMING,WY,Laramie County School District #1,Davis Elementary,17,17,0,2,2,...,0,0,0,0.0,1,16,0,0,0,0
5086,96081,WYOMING,WY,Laramie County School District #1,Deming Elementary,8,8,0,2,0,...,0,0,0,0.0,1,16,0,0,0,0
5087,96082,WYOMING,WY,Laramie County School District #1,Dildine Elementary,26,41,2,2,2,...,0,6,0,1.8,1,16,0,0,0,0
5088,96083,WYOMING,WY,Laramie County School District #1,Fairview Elementary,11,14,0,0,0,...,0,0,0,0.0,1,16,0,0,0,0
5089,96084,WYOMING,WY,Laramie County School District #1,Gilchrist Elementary,2,5,0,2,0,...,0,0,0,0.0,1,16,0,0,0,0
5090,96085,WYOMING,WY,Laramie County School District #1,Goins Elementary,53,50,5,2,2,...,0,0,0,0.0,1,16,0,0,0,0
5091,96086,WYOMING,WY,Laramie County School District #1,Hebard Elementary,44,29,2,0,0,...,0,2,2,0.8,2,17,0,0,0,0
5092,96087,WYOMING,WY,Laramie County School District #1,Henderson Elementary,29,23,2,2,2,...,0,0,0,0.0,1,16,0,0,0,0
5093,96088,WYOMING,WY,Laramie County School District #1,Hobbs Elementary,29,32,0,0,8,...,0,2,15,2.1,1,16,0,0,0,0
5094,96089,WYOMING,WY,Laramie County School District #1,Clawson Elementary,0,0,0,0,0,...,0,0,0,0.0,1,11,0,0,0,0
5095,96090,WYOMING,WY,Laramie County School District #1,Jessup Elementary,14,11,0,0,2,...,0,2,0,0.6,3,18,0,0,0,0
5096,96091,WYOMING,WY,Laramie County School District #1,Lebhart Elementary,14,14,0,0,0,...,0,0,0,0.0,1,16,0,0,0,0
5097,96092,WYOMING,WY,Laramie County School District #1,Miller Elementary,8,2,0,2,0,...,0,0,0,0.0,1,15,0,0,0,0
5098,96093,WYOMING,WY,Laramie County School District #1,Pioneer Park Elementary,20,20,2,0,2,...,0,0,0,0.0,1,16,0,0,0,0
5099,96094,WYOMING,WY,Laramie County School District #1,Rossman Elementary,38,38,2,2,2,...,0,2,0,0.6,3,18,0,0,0,0

In [39]:
school_layout_new.keys()

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
       'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
       'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
       'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
       'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
       'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
       'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
       'DISABLE_FEMALE'],
      dtype='object')

In [38]:
cols = ['SCH_ENR_AS', 'SCH_ENR_BL', 'SCH_ENR_HP', 'SCH_ENR_WH',
       'SCH_ENR_TR', 'SCH_ENR_HI', 'SCH_ENR_AM']
school_layout_new = school_layout_new.drop(columns = cols)
# school_layout = school_layout.drop(columns=['SCH_ENR_HI_M','SCH_ENR_HI_F','SCH_ENR_AM_M','SCH_ENR_AM_F','SCH_ENR_AS_M','SCH_ENR_AS_F',
#                             'SCH_ENR_BL_M','SCH_ENR_BL_F','SCH_ENR_TR_M','SCH_ENR_TR_F','SCH_ENR_HP_M','SCH_ENR_HP_F',
#                             'SCH_ENR_WH_M','SCH_ENR_WH_F'])

In [44]:
school_layout_new.rename(columns={'SCH_ENR_HI_M':'SCH_ENR_HI TOT_ENR_M','SCH_ENR_HI_F':'SCH_ENR_HI TOT_ENR_F', 
                                  'SCH_ENR_AS_M':'SCH_ENR_AS TOT_ENR_M', 'SCH_ENR_AS_F':"SCH_ENR_AS TOT_ENR_F",
                        'SCH_ENR_BL_M':"SCH_ENR_BL TOT_ENR_M", "SCH_ENR_BL_F":"SCH_ENR_BL TOT_ENR_F",
                        'SCH_ENR_HP_M':"SCH_ENR_HP TOT_ENR_M", 'SCH_ENR_HP_F':"SCH_ENR_HP TOT_ENR_F",
                        'SCH_ENR_WH_M':"SCH_ENR_WH TOT_ENR_M", 'SCH_ENR_WH_F':"SCH_ENR_WH TOT_ENR_F",
                        'SCH_ENR_TR_M':"SCH_ENR_TR TOT_ENR_M", 'SCH_ENR_TR_F':"SCH_ENR_TR TOT_ENR_F",
                        'SCH_ENR_AM_M':"SCH_ENR_AM TOT_ENR_M", 'SCH_ENR_AM_F':"SCH_ENR_AM TOT_ENR_F",          
                                 },inplace=True)

In [47]:
df2 = pd.melt(school_layout_new, id_vars=['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F','TOT_ENR', 'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH',
       'VAL_BL', 'VAL_HP', 'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE',
       'RACE_SCORE', 'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES',
       'AP_SCORE', 'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE',
       'TOT_ARR', 'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES',
       'OFFENSES_SCORE', 'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE',
       'DISABLE_MALE', 'DISABLE_FEMALE'],
                  var_name="Race_Gender", value_name="Value")

In [36]:
# df2 = pd.melt(school_layout_new, id_vars=['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
#        'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
#        'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
#        'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
#        'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
#        'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
#        'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
#        'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
#        'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
#        'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
#        'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
#        'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
#        'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
#        'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
#        'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
#        'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F','TOT_ENR', 'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH',
#        'VAL_BL', 'VAL_HP', 'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE',
#        'RACE_SCORE', 'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES',
#        'AP_SCORE', 'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE',
#        'TOT_ARR', 'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES',
#        'OFFENSES_SCORE', 'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE',
#        'DISABLE_MALE', 'DISABLE_FEMALE'],
#                   var_name="Race", value_name="Value")

In [41]:
print(df2.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
       'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
       'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
       'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
       'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
       'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
       'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
       'DISABLE_FEMALE', 'Race', 'Value'],
      dtype='object')

In [38]:
# df2 = pd.melt(df2, id_vars=['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
#        'SCH_APENR_IND', 'SCH_APCOURSES',
#        'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
#        'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
#        'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
#        'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
#        'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
#        'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
#        'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
#        'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
#        'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
#        'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
#        'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
#        'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
#        'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
#        'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
#        'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
#        'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
#        'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
#        'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
#        'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
#        'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
#        'DISABLE_FEMALE', 'Race', 'Value'],
#               var_name="Gender", value_name="GenderValue")

In [39]:
# print(df2.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
       'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
       'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
       'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
       'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
       'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
       'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
       'DISABLE_FEMALE', 'Race', 'Value', 'Gender', 'GenderValue'],
      dtype='object')

In [48]:
df2.Race_Gender.unique()

array(['SCH_ENR_HI TOT_ENR_M', 'SCH_ENR_HI TOT_ENR_F',
       'SCH_ENR_AM TOT_ENR_M', 'SCH_ENR_AM TOT_ENR_F',
       'SCH_ENR_AS TOT_ENR_M', 'SCH_ENR_AS TOT_ENR_F',
       'SCH_ENR_HP TOT_ENR_M', 'SCH_ENR_HP TOT_ENR_F',
       'SCH_ENR_BL TOT_ENR_M', 'SCH_ENR_BL TOT_ENR_F',
       'SCH_ENR_WH TOT_ENR_M', 'SCH_ENR_WH TOT_ENR_F',
       'SCH_ENR_TR TOT_ENR_M', 'SCH_ENR_TR TOT_ENR_F'], dtype=object)

In [49]:
df2[['Race','Gender']] = df2.Race_Gender.str.split(" ",expand=True,)

In [53]:
df2['GenderValue'] = df2.Value

In [55]:
df2 = df2.drop(columns=['Race_Gender'])

In [56]:
df2.keys()

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
       'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
       'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
       'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
       'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
       'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
       'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
       'DISABLE_FEMALE', 'Value', 'Race', 'Gender', 'GenderValue'],
      dtype='object')

In [57]:
df2.Gender.unique()

array(['TOT_ENR_M', 'TOT_ENR_F'], dtype=object)

In [58]:
df2.to_csv("all_states_racegender.csv")

In [59]:
df2.count()

Unnamed: 0                 71400
LEA_STATE_NAME             71400
LEA_STATE                  71400
LEA_NAME                   71400
SCH_NAME                   71400
TOT_ENR_M                  71400
TOT_ENR_F                  71400
SCH_APENR_IND              71400
SCH_APCOURSES              71400
TOT_APENR_M                71400
TOT_APENR_F                71400
TOT_SATACT_M               71400
TOT_SATACT_F               71400
TOT_HBREPORTED_SEX_M       71400
TOT_HBREPORTED_SEX_F       71400
TOT_HBREPORTED_DIS_M       71400
TOT_HBREPORTED_DIS_F       71400
TOT_HBREPORTED_RAC_M       71400
TOT_HBREPORTED_RAC_F       71400
TOT_HBDISCIPLINED_SEX_M    71400
TOT_HBDISCIPLINED_SEX_F    71400
TOT_HBDISCIPLINED_RAC_M    71400
TOT_HBDISCIPLINED_RAC_F    71400
TOT_HBDISCIPLINED_DIS_M    71400
TOT_HBDISCIPLINED_DIS_F    71400
TOT_DISCWODIS_ISS_M        71400
TOT_DISCWODIS_ISS_F        71400
TOT_DISCWDIS_ISS_IDEA_M    71400
TOT_DISCWDIS_ISS_IDEA_F    71400
TOT_DISCWODIS_ARR_M        71400
                           ...
VAL_BL                     71400
VAL_HP                     71400
VAL_TR                     71400
VAL_HI                     71400
VAL_AS                     71400
VAL_AM                     71400
VAL_RACE                   71400
RACE_SCORE                 71400
VAL_GENDER                 71400
GENDER_SCORE               71400
VAL_AP_COURSES             71400
AP_SCORE                   71400
VAL_SATACT_COURSES         71400
SATACT_SCORE               71400
COURSES_SCORE              71400
TOT_ARR                    71400
TOT_EXP                    71400
TOT_HARR                   71400
TOT_SUSP                   71400
VAL_OFFENSES               71400
OFFENSES_SCORE             71400
SCHOOL_SCORE               71400
ABLE_MALE                  71400
ABLE_FEMALE                71400
DISABLE_MALE               71400
DISABLE_FEMALE             71400
Value                      71400
Race                       71400
Gender                     71400
GenderValue                71400
Length: 78, dtype: int64

### NOTE:
1. Calculate scores for race
2. calculate scores for gender  : absolute diff between tot_enr_m and tot_enr_F divide by tot-enr : do same scoring as race
3. Calculate score for AP : ap-tot/tot-enr . score is reverse of race score. do same thing for SAT/ACT and take avg of both for tot score.
4. Calculate score for offenses : 
Ignore IDEA columns. Calculate Tot by adding M+F. AT the end one column each for arrest(0.4), expulsion(0.2), suspension(0.1), harrasment(0.3). Multiply by weights (given) divide by enrollment and then assign scores similar to race. lower the better.
5. Total score : Avg of above
6. Change all negative value to 0s, drop schools with tot-enr = 0

7. List of final columns we need: 4 scores of race,gender,ap and offenses, 1 overall score, tot_enr, tot-enr-m, tot-enr-f, race, value of the race, all idefication columns(refer google doc),

```
var diffDimension = ndx.dimension(function(d){
		return Math.abs(d.TOT_ENR_M - d.TOT_ENR_F);
	});
var diffGroup = diffDimension.group().reduceCount();
subjectChart
    .width(768)
        .height(480)
        .x(d3.scale.linear().domain([50,100]))
        .brushOn(false)
        .dimension(diffDimension)
        .group(diffGroup); 
dc.renderAll();
dc.redrawAll();        
```