In [91]:
import pandas as pd
import numpy as np
import math

In [92]:
school_layout = pd.read_csv('all_states_data.csv', encoding='latin')

In [93]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F'],
      dtype='object')

In [94]:
school_layout.head()

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,SCH_ENR_HI_M,SCH_ENR_HI_F,SCH_ENR_AM_M,SCH_ENR_AM_F,SCH_ENR_AS_M,...,TOT_DISCWODIS_EXPWE_M,TOT_DISCWODIS_EXPWE_F,TOT_DISCWODIS_EXPWOE_M,TOT_DISCWODIS_EXPWOE_F,TOT_DISCWDIS_EXPWOE_IDEA_M,TOT_DISCWDIS_EXPWE_IDEA_M,TOT_DISCWDIS_EXPWE_IDEA_F,TOT_DISCWDIS_EXPWOE_IDEA_F,TOT_DISCWDIS_EXPZT_IDEA_M,TOT_DISCWDIS_EXPZT_IDEA_F
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,5,0,0,0,0,...,-9,-9,0,0,-9,-9,-9,-9,-9,-9
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,0,0,0,0,0,...,-9,-9,0,0,-9,-9,-9,-9,-9,-9
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,0,0,14,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,2,0,0,0,0,...,-9,-9,0,0,-9,-9,-9,-9,-9,-9
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,140,143,2,0,0,...,0,0,0,0,0,0,0,0,0,0

In [95]:
#These columns are used for reporting harrassment and bullying
#school_layout = school_layout.drop(columns=['TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_DIS_M',
#                           'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F'])

In [96]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F'],
      dtype='object')

### Convert all the columns with values -9 to 0.

In [97]:
school_layout.replace(-9,0, inplace=True)
school_layout.replace('-9',0, inplace=True)
school_layout.replace(-10,0, inplace=True)
school_layout.replace(-20,0, inplace=True)
school_layout.replace(-5, 0, inplace=True)

In [98]:
school_layout['SCH_ENR_AS'] = school_layout['SCH_ENR_AS_F']+school_layout['SCH_ENR_AS_M']
school_layout['SCH_ENR_BL'] = school_layout['SCH_ENR_BL_M']+school_layout['SCH_ENR_BL_F']
school_layout['SCH_ENR_HP'] = school_layout['SCH_ENR_HP_M']+school_layout['SCH_ENR_HP_F']
school_layout['SCH_ENR_WH'] = school_layout['SCH_ENR_WH_M']+school_layout['SCH_ENR_WH_F']
school_layout['SCH_ENR_TR'] = school_layout['SCH_ENR_TR_M']+school_layout['SCH_ENR_TR_F']
school_layout['SCH_ENR_HI'] = school_layout['SCH_ENR_HI_M']+school_layout['SCH_ENR_HI_F']
school_layout['SCH_ENR_AM'] = school_layout['SCH_ENR_AM_M']+school_layout['SCH_ENR_AM_F']

In [99]:
display(school_layout['SCH_ENR_HP'].head())

0    2
1    0
2    0
3    0
4    0
Name: SCH_ENR_HP, dtype: int64

In [100]:
school_layout = school_layout.drop(columns=['SCH_ENR_HI_M','SCH_ENR_HI_F','SCH_ENR_AM_M','SCH_ENR_AM_F','SCH_ENR_AS_M','SCH_ENR_AS_F',
                            'SCH_ENR_BL_M','SCH_ENR_BL_F','SCH_ENR_TR_M','SCH_ENR_TR_F','SCH_ENR_HP_M','SCH_ENR_HP_F',
                            'SCH_ENR_WH_M','SCH_ENR_WH_F'])

In [101]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'SCH_ENR_AS',
       'SCH_ENR_BL', 'SCH_ENR_HP', 'SCH_ENR_WH', 'SCH_ENR_TR', 'SCH_ENR_HI',
       'SCH_ENR_AM'],
      dtype='object')

### Create the following new fields. 
1. Total Enrollment (TOT_ENR) = Enrollment including male and female students.
2. Create a new field called Average Enrollment (AVG_ENR) = Total Enrollment/7 (because there are 7 races).  
3. Total SATACT = total number of TOT_SATACT_M + TOT_SATACT_F
4. VAL_SAT = TOT_SATACT/TOT_ENR

In [102]:
school_layout['TOT_ENR'] = school_layout['TOT_ENR_M'] + school_layout['TOT_ENR_F']

In [103]:
school_layout['AVG_ENR'] = school_layout['TOT_ENR']/7
school_layout['TOT_SATACT'] = school_layout['TOT_SATACT_M'] + school_layout['TOT_SATACT_F']
school_layout['VAL_SAT'] = school_layout['TOT_SATACT']/school_layout['TOT_ENR']

In [104]:
school_layout['VAL_WH'] = (school_layout['SCH_ENR_WH'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_BL'] = (school_layout['SCH_ENR_BL'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_HP'] = (school_layout['SCH_ENR_HP'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_TR'] = (school_layout['SCH_ENR_TR'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_HI'] = (school_layout['SCH_ENR_HI'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_AS'] = (school_layout['SCH_ENR_AS'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']
school_layout['VAL_AM'] = (school_layout['SCH_ENR_AM'] - school_layout['AVG_ENR']).abs()/school_layout['TOT_ENR']

### Calculate score based on the VAL where
1. 0.0-0.2 = 5 
2. 0.2-0.4 = 4
3. 0.4-0.6 = 3
4. 0.6-0.8 = 2
5. 0.8-1.0 = 1 

## TODO: 
1. change the scoring to be better reflective of the percentages

In [105]:
school_layout['VAL_RACE'] = (school_layout['VAL_WH']+school_layout['VAL_BL']+\
    school_layout['VAL_HP']+school_layout['VAL_TR']+school_layout['VAL_HI']+\
    school_layout['VAL_AS']+school_layout['VAL_AM'])/7

In [106]:
def score(school_layout):
    val = school_layout['VAL_RACE']
    if val>0 and val<=0.2:
        return 5
    elif val>0.2 and val<=0.4:
        return 4
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 2
    else:
        return 1

def score3(school_layout):
    val = school_layout['VAL_GENDER']
    if val>0 and val<=0.2:
        return 5
    elif val>0.2 and val<=0.4:
        return 4
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 2
    else:
        return 1
    
def score5(school_layout):
    val = school_layout['VAL_OFFENSES']
    if val>0 and val<=0.2:
        return 5
    elif val>0.2 and val<=0.4:
        return 4
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 2
    else:
        return 1

In [107]:
def score2(school_layout):
    val = school_layout['VAL_AP_COURSES']
    if val>0 and val<=0.2:
        return 1
    elif val>0.2 and val<=0.4:
        return 2
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 4
    else:
        return 5

def score4(school_layout):
    val = school_layout['VAL_SATACT_COURSES']
    if val>0 and val<=0.2:
        return 1
    elif val>0.2 and val<=0.4:
        return 2
    elif val>0.4 and val<=0.6:
        return 3
    elif val>0.6 and val<=0.8:
        return 4
    else:
        return 5

In [108]:
school_layout['RACE_SCORE'] = school_layout.apply(score, axis=1)

In [109]:
display(school_layout['RACE_SCORE'].unique())

array([5, 4, 1], dtype=int64)

In [110]:
school_layout.head()

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,TOT_ENR_M,TOT_ENR_F,SCH_APENR_IND,SCH_APCOURSES,TOT_APENR_M,...,VAL_SAT,VAL_WH,VAL_BL,VAL_HP,VAL_TR,VAL_HI,VAL_AS,VAL_AM,VAL_RACE,RACE_SCORE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,128,0,0,0,0,...,0.078125,0.247768,0.411830,0.127232,0.142857,0.103795,0.142857,0.142857,0.188457,5
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,52,0,0,0,0,...,0.076923,0.126374,0.587912,0.142857,0.142857,0.142857,0.142857,0.142857,0.204082,4
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,908,0,No,0,0,...,0.014317,0.212870,0.467275,0.142857,0.124135,0.142857,0.142857,0.127439,0.194327,5
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,38,0,0,0,0,...,0.105263,0.225564,0.304511,0.142857,0.011278,0.090226,0.142857,0.142857,0.151450,5
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,358,346,0,0,0,...,0.000000,0.395495,0.120130,0.142857,0.111607,0.259131,0.140016,0.140016,0.187036,5

In [111]:
school_layout['VAL_GENDER']=(school_layout['TOT_ENR_M'] - school_layout['TOT_ENR_F']).abs()/school_layout['TOT_ENR']
school_layout['GENDER_SCORE'] = school_layout.apply(score3, axis=1)

In [112]:
school_layout['VAL_AP_COURSES'] = (school_layout['TOT_APENR_M'] + school_layout['TOT_APENR_F'])/school_layout['TOT_ENR']
school_layout['AP_SCORE'] = school_layout.apply(score2, axis=1)
school_layout['VAL_SATACT_COURSES'] = (school_layout['TOT_SATACT_M'] + school_layout['TOT_SATACT_F'])/school_layout['TOT_ENR']
school_layout['SATACT_SCORE'] = school_layout.apply(score4, axis=1)
school_layout['COURSES_SCORE'] = (school_layout['AP_SCORE']+school_layout['AP_SCORE'])//2

In [113]:
school_layout['TOT_ARR'] = (school_layout['TOT_DISCWODIS_ARR_M'] + school_layout['TOT_DISCWODIS_ARR_F'])
school_layout['TOT_EXP'] = school_layout['TOT_DISCWODIS_EXPWE_M'] + school_layout['TOT_DISCWODIS_EXPWE_F'] +school_layout['TOT_DISCWODIS_EXPWOE_M'] + school_layout['TOT_DISCWODIS_EXPWOE_F']
school_layout['TOT_HARR'] = school_layout['TOT_HBDISCIPLINED_SEX_M'] + school_layout['TOT_HBDISCIPLINED_SEX_F'] + school_layout['TOT_HBDISCIPLINED_RAC_M'] + school_layout['TOT_HBDISCIPLINED_RAC_F']+ school_layout['TOT_HBDISCIPLINED_DIS_M'] + school_layout['TOT_HBDISCIPLINED_DIS_F']
school_layout['TOT_SUSP'] = school_layout['TOT_DISCWODIS_ISS_M'] + school_layout['TOT_DISCWODIS_ISS_F']
school_layout['VAL_OFFENSES'] = (school_layout['TOT_ARR']*0.4 + school_layout['TOT_EXP']*0.2 + school_layout['TOT_SUSP']*0.1  + school_layout['TOT_HARR']*0.3)
school_layout['OFFENSES_SCORE'] = school_layout.apply(score5, axis=1)

In [114]:
school_layout['SCHOOL_SCORE'] = (school_layout['RACE_SCORE'] + school_layout['GENDER_SCORE'] + school_layout['COURSES_SCORE']
    + school_layout['OFFENSES_SCORE'])//4.0

In [115]:
display(school_layout.head())

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,TOT_ENR_M,TOT_ENR_F,SCH_APENR_IND,SCH_APCOURSES,TOT_APENR_M,...,VAL_SATACT_COURSES,SATACT_SCORE,COURSES_SCORE,TOT_ARR,TOT_EXP,TOT_HARR,TOT_SUSP,VAL_OFFENSES,OFFENSES_SCORE,SCHOOL_SCORE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,128,0,0,0,0,...,0.078125,1,5,0,0,0,0,0.0,1,3
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,52,0,0,0,0,...,0.076923,1,5,0,0,0,0,0.0,1,2
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,908,0,No,0,0,...,0.014317,1,5,0,0,6,0,1.8,1,3
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,38,0,0,0,0,...,0.105263,1,5,0,0,0,0,0.0,1,3
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,358,346,0,0,0,...,0.000000,5,5,0,0,0,115,11.5,1,4

In [116]:
display(school_layout['COURSES_SCORE'].unique())
display(school_layout['RACE_SCORE'].unique())
display(school_layout['OFFENSES_SCORE'].unique())
display(school_layout['GENDER_SCORE'].unique())

array([5, 1, 2, 3, 4], dtype=int64)

array([5, 4, 1], dtype=int64)

array([1, 2, 4, 5, 3], dtype=int64)

array([1, 5, 4, 3, 2], dtype=int64)

In [117]:
school_layout['SCHOOL_SCORE'].unique()

array([3, 2, 4, 5, 1], dtype=int64)

In [118]:
school_layout.fillna(0)

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,TOT_ENR_M,TOT_ENR_F,SCH_APENR_IND,SCH_APCOURSES,TOT_APENR_M,...,VAL_SATACT_COURSES,SATACT_SCORE,COURSES_SCORE,TOT_ARR,TOT_EXP,TOT_HARR,TOT_SUSP,VAL_OFFENSES,OFFENSES_SCORE,SCHOOL_SCORE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,128,0,0,0,0,...,0.078125,1,5,0,0,0,0,0.0,1,3
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,52,0,0,0,0,...,0.076923,1,5,0,0,0,0,0.0,1,2
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,908,0,No,0,0,...,0.014317,1,5,0,0,6,0,1.8,1,3
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,38,0,0,0,0,...,0.105263,1,5,0,0,0,0,0.0,1,3
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,358,346,0,0,0,...,0.000000,5,5,0,0,0,115,11.5,1,4
5,5,ALABAMA,AL,Albertville City,Albertville High Sch,645,650,Yes,8,70,...,0.234749,2,1,2,0,0,6,1.4,1,3
6,6,ALABAMA,AL,Albertville City,Evans Elem Sch,381,389,0,0,0,...,0.000000,5,5,0,0,2,2,0.8,2,4
7,7,ALABAMA,AL,Albertville City,Albertville Elem Sch,430,417,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,4
8,8,ALABAMA,AL,Albertville City,Big Spring Lake Kinderg Sch,264,234,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,4
9,9,ALABAMA,AL,Albertville City,Albertville Primary Sch,555,534,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,4
10,10,ALABAMA,AL,Marshall County,Kate Duncan Smith DAR Middle,235,210,0,0,0,...,0.000000,5,5,0,29,0,24,8.2,1,3
11,11,ALABAMA,AL,Marshall County,Asbury Sch,289,250,Yes,5,31,...,0.224490,2,1,2,33,2,86,16.6,1,3
12,12,ALABAMA,AL,Marshall County,Claysville Jr High Sch,64,65,0,0,0,...,0.000000,5,5,0,6,0,2,1.4,1,4
13,13,ALABAMA,AL,Marshall County,Douglas Elem Sch,261,240,0,0,0,...,0.000000,5,5,0,13,2,12,4.4,1,3
14,14,ALABAMA,AL,Marshall County,Douglas High Sch,310,284,Yes,5,59,...,0.476431,3,2,4,36,6,174,28.0,1,3
15,15,ALABAMA,AL,Marshall County,Brindlee Mountain Elementary School,131,123,0,0,0,...,0.000000,5,5,0,0,0,15,1.5,1,3
16,16,ALABAMA,AL,Marshall County,Kate D Smith DAR High Sch,236,223,Yes,4,59,...,0.505447,3,2,0,47,0,73,16.7,1,3
17,17,ALABAMA,AL,Marshall County,Brindlee Mountain Primary School,128,102,0,0,0,...,0.000000,5,5,0,2,0,0,0.4,4,4
18,18,ALABAMA,AL,Marshall County,Robert D Sloman Primary,258,238,0,0,0,...,0.000000,5,5,0,7,0,0,1.4,1,4
19,19,ALABAMA,AL,Marshall County,Brindlee Mt Middle Sch,130,129,0,0,0,...,0.000000,5,5,0,27,0,51,10.5,1,3
20,20,ALABAMA,AL,Marshall County,Brindlee Mt High Sch,187,176,Yes,5,20,...,0.473829,3,1,2,5,0,80,9.8,1,2
21,21,ALABAMA,AL,Marshall County,Kate D Smith DAR Elem Sch,215,223,0,0,0,...,0.000000,5,5,0,2,0,2,0.6,2,4
22,22,ALABAMA,AL,Marshall County,Douglas Middle Sch,250,218,0,0,0,...,0.000000,5,5,0,66,0,94,22.6,1,4
23,23,ALABAMA,AL,Marshall County,Asbury Elem Sch,237,259,0,0,0,...,0.000000,5,5,0,0,0,4,0.4,4,4
24,24,ALABAMA,AL,Hoover City,Trace Crossings Elem Sch,334,238,0,0,0,...,0.000000,5,5,0,0,0,2,0.2,5,5
25,25,ALABAMA,AL,Hoover City,Greystone Elem Sch,307,256,0,0,0,...,0.000000,5,5,0,0,0,2,0.2,5,5
26,26,ALABAMA,AL,Hoover City,Hoover High Sch,1518,1449,Yes,22,202,...,0.416245,3,1,0,0,2,2,0.8,2,3
27,27,ALABAMA,AL,Hoover City,Berry Middle Sch,586,582,No,0,0,...,0.000000,5,5,0,0,0,2,0.2,5,5
28,28,ALABAMA,AL,Hoover City,South Shades Crest Elem Sch,318,295,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,4
29,29,ALABAMA,AL,Hoover City,Robert F Bumpus Middle Sch,414,414,0,0,0,...,0.000000,5,5,0,0,2,4,1.0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96330,96330,WYOMING,WY,Sweetwater County School District #2,Washington Elementary,120,102,0,0,0,...,0.000000,5,5,0,0,0,4,0.4,4,4
96331,96331,WYOMING,WY,Sweetwater County School District #2,Lincoln Middle School,203,230,0,0,0,...,0.000000,5,5,0,0,2,56,6.2,1,4
96332,96332,WYOMING,WY,Sweetwater County School District #2,Jackson Elementary,116,141,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,4
96333,96333,WYOMING,WY,Sweetwater County School District #2,Truman Elementary,155,142,0,0,0,...,0.000000,5,5,0,0,0,2,0.2,5,5
96334,96334,WYOMING,WY,Sweetwater County School District #2,Harrison Elementary,137,143,0,0,0,...,0.000000,5,5,0,0,0,8,0.8,2,4
96335,96335,WYOMING,WY,Sweetwater County School District #2,Thoman Ranch Elementary,0,2,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,2
96336,96336,WYOMING,WY,Washakie County School District #2,Ten Sleep K-12,60,50,Yes,1,2,...,0.145455,1,1,0,0,0,2,0.2,5,3
96337,96337,WYOMING,WY,Teton County School District #1,Colter Elementary,290,270,0,0,0,...,0.000000,5,5,0,0,0,6,0.6,2,4
96338,96338,WYOMING,WY,Teton County School District #1,Jackson Elementary,301,290,0,0,0,...,0.000000,5,5,0,0,0,4,0.4,4,4
96339,96339,WYOMING,WY,Teton County School District #1,Jackson Hole High School,324,316,Yes,12,67,...,0.000000,5,2,0,0,0,35,3.5,1,3
96340,96340,WYOMING,WY,Teton County School District #1,Jackson Hole Middle School,298,288,0,0,0,...,0.000000,5,5,0,0,0,19,1.9,1,4
96341,96341,WYOMING,WY,Teton County School District #1,Alta Elementary,26,19,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,3
96342,96342,WYOMING,WY,Teton County School District #1,Kelly Elementary,26,20,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,3
96343,96343,WYOMING,WY,Teton County School District #1,Moran Elementary,10,10,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,2
96344,96344,WYOMING,WY,Teton County School District #1,Wilson Elementary,110,125,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,3
96345,96345,WYOMING,WY,Teton County School District #1,Summit High School,36,18,No,0,0,...,0.000000,5,5,0,0,0,12,1.2,1,3
96346,96346,WYOMING,WY,Weston County School District #7,Upton Middle School,34,24,0,0,0,...,0.000000,5,5,0,2,0,7,1.1,1,3
96347,96347,WYOMING,WY,Weston County School District #7,Upton Elementary,63,66,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,3
96348,96348,WYOMING,WY,Weston County School District #7,Upton High School,49,51,Yes,1,2,...,0.240000,2,1,0,0,0,4,0.4,4,3
96349,96349,WYOMING,WY,Washakie County School District #1,Worland High School,203,197,Yes,5,11,...,0.272500,2,1,0,0,0,52,5.2,1,3
96350,96350,WYOMING,WY,Washakie County School District #1,Worland Middle School,171,159,0,0,0,...,0.000000,5,5,0,0,0,20,2.0,1,4
96351,96351,WYOMING,WY,Washakie County School District #1,East Side Elementary,93,120,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,4
96352,96352,WYOMING,WY,Washakie County School District #1,South Side Elementary,103,111,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,4
96353,96353,WYOMING,WY,Washakie County School District #1,West Side Elementary,104,98,0,0,0,...,0.000000,5,5,0,0,0,2,0.2,5,5
96354,96354,WYOMING,WY,Northeast Wyoming BOCES,Powder River Basin Children's Center,28,13,No,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,3
96355,96355,WYOMING,WY,Region V BOCES,C-Bar-V Ranch,41,9,No,0,0,...,0.140000,1,5,0,0,19,0,5.7,1,3
96356,96356,WYOMING,WY,Wyoming Department of Family Services,Wyoming Girls School,0,82,0,0,0,...,0.000000,5,5,0,0,0,0,0.0,1,3
96357,96357,WYOMING,WY,Wyoming Department of Family Services,Wyoming Boys School,187,0,0,0,0,...,0.117647,1,5,0,0,0,0,0.0,1,3
96358,96358,WYOMING,WY,Youth Emergency Services Inc. - Administration...,Youth Emergency Services Inc.,21,18,No,0,0,...,0.307692,2,5,0,0,0,7,0.7,2,4
96359,96359,WYOMING,WY,Saint Stephen's Indian School Admin Office,Saint Stephen's Indian School,110,107,No,0,0,...,0.142857,1,5,0,0,7,67,8.8,1,3

In [119]:
print(school_layout.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'SCH_ENR_AS',
       'SCH_ENR_BL', 'SCH_ENR_HP', 'SCH_ENR_WH', 'SCH_ENR_TR', 'SCH_ENR_HI',
       'SCH_ENR_AM', 'TOT_ENR', 'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH',
       'VAL_BL', 'VAL_HP', 'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE',
       'RACE_SCORE', 'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES',
       'AP_SCORE', 'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE',
       'TOT_ARR', 'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES',
       'OFFENSES_SCORE', 'SCHOOL_SCORE'],
      dtype='object')

In [120]:
print(school_layout.index)
print(school_layout['LEA_STATE'].unique())

RangeIndex(start=0, stop=96360, step=1)
['AL' 'AK' 'AZ' 'AR' 'CA' 'CO' 'CT' 'DE' 'DC' 'FL' 'GA' 'HI' 'ID' 'IL'
 'IN' 'IA' 'KS' 'KY' 'LA' 'ME' 'MD' 'MA' 'MI' 'MN' 'MS' 'MO' 'MT' 'NE'
 'NV' 'NH' 'NJ' 'NM' 'NY' 'NC' 'ND' 'OH' 'OK' 'OR' 'PA' 'RI' 'SC' 'SD'
 'TN' 'TX' 'UT' 'VT' 'VA' 'WA' 'WV' 'WI' 'WY']

Choose same number of schools from each of the states.

In [121]:
states = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA', 'HI', 'ID', 'IL', \
 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', \
 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', \
 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
school_layout_new = pd.DataFrame()
for state in states:
    df = school_layout.loc[school_layout['LEA_STATE']==state]
    df = df[:25]
    school_layout_new = school_layout_new.append(df, ignore_index=True)

```
import random
school_layout_small = school_layout.sample(n=600)
display(school_layout_small['LEA_STATE'].unique())
```

In [122]:
school_layout_new['LEA_STATE'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [123]:
school_layout_new['ABLE_MALE']=school_layout_new['TOT_DISCWODIS_EXPWE_M']+school_layout_new['TOT_DISCWODIS_EXPWOE_M']
school_layout_new['ABLE_FEMALE']=school_layout_new['TOT_DISCWODIS_EXPWE_F']+school_layout_new['TOT_DISCWODIS_EXPWOE_F']
school_layout_new['DISABLE_MALE']=school_layout_new['TOT_DISCWDIS_EXPWE_IDEA_M']+school_layout_new['TOT_DISCWDIS_EXPWOE_IDEA_M']
school_layout_new['DISABLE_FEMALE']=school_layout_new['TOT_DISCWDIS_EXPWE_IDEA_F']+school_layout_new['TOT_DISCWDIS_EXPWOE_IDEA_F']

In [124]:
school_layout_new

,Unnamed: 0,LEA_STATE_NAME,LEA_STATE,LEA_NAME,SCH_NAME,TOT_ENR_M,TOT_ENR_F,SCH_APENR_IND,SCH_APCOURSES,TOT_APENR_M,...,TOT_EXP,TOT_HARR,TOT_SUSP,VAL_OFFENSES,OFFENSES_SCORE,SCHOOL_SCORE,ABLE_MALE,ABLE_FEMALE,DISABLE_MALE,DISABLE_FEMALE
0,0,ALABAMA,AL,Alabama Youth Services,Wallace Sch - Mt Meigs Campus,128,0,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1,1,ALABAMA,AL,Alabama Youth Services,McNeel Sch - Vacca Campus,52,0,0,0,0,...,0,0,0,0.0,1,2,0,0,0,0
2,2,ALABAMA,AL,Alabama Youth Services,Alabama Youth Services,908,0,No,0,0,...,0,6,0,1.8,1,3,0,0,0,0
3,3,ALABAMA,AL,Alabama Youth Services,AUTAUGA CAMPUS,38,0,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
4,4,ALABAMA,AL,Albertville City,Albertville Middle School,358,346,0,0,0,...,0,0,115,11.5,1,4,0,0,0,0
5,5,ALABAMA,AL,Albertville City,Albertville High Sch,645,650,Yes,8,70,...,0,0,6,1.4,1,3,0,0,0,0
6,6,ALABAMA,AL,Albertville City,Evans Elem Sch,381,389,0,0,0,...,0,2,2,0.8,2,4,0,0,0,0
7,7,ALABAMA,AL,Albertville City,Albertville Elem Sch,430,417,0,0,0,...,0,0,0,0.0,1,4,0,0,0,0
8,8,ALABAMA,AL,Albertville City,Big Spring Lake Kinderg Sch,264,234,0,0,0,...,0,0,0,0.0,1,4,0,0,0,0
9,9,ALABAMA,AL,Albertville City,Albertville Primary Sch,555,534,0,0,0,...,0,0,0,0.0,1,4,0,0,0,0
10,10,ALABAMA,AL,Marshall County,Kate Duncan Smith DAR Middle,235,210,0,0,0,...,29,0,24,8.2,1,3,20,9,13,2
11,11,ALABAMA,AL,Marshall County,Asbury Sch,289,250,Yes,5,31,...,33,2,86,16.6,1,3,24,9,6,0
12,12,ALABAMA,AL,Marshall County,Claysville Jr High Sch,64,65,0,0,0,...,6,0,2,1.4,1,4,4,2,2,2
13,13,ALABAMA,AL,Marshall County,Douglas Elem Sch,261,240,0,0,0,...,13,2,12,4.4,1,3,13,0,2,0
14,14,ALABAMA,AL,Marshall County,Douglas High Sch,310,284,Yes,5,59,...,36,6,174,28.0,1,3,34,2,2,0
15,15,ALABAMA,AL,Marshall County,Brindlee Mountain Elementary School,131,123,0,0,0,...,0,0,15,1.5,1,3,0,0,8,0
16,16,ALABAMA,AL,Marshall County,Kate D Smith DAR High Sch,236,223,Yes,4,59,...,47,0,73,16.7,1,3,34,13,4,2
17,17,ALABAMA,AL,Marshall County,Brindlee Mountain Primary School,128,102,0,0,0,...,2,0,0,0.4,4,4,2,0,0,0
18,18,ALABAMA,AL,Marshall County,Robert D Sloman Primary,258,238,0,0,0,...,7,0,0,1.4,1,4,7,0,2,0
19,19,ALABAMA,AL,Marshall County,Brindlee Mt Middle Sch,130,129,0,0,0,...,27,0,51,10.5,1,3,20,7,0,0
20,20,ALABAMA,AL,Marshall County,Brindlee Mt High Sch,187,176,Yes,5,20,...,5,0,80,9.8,1,2,5,0,2,0
21,21,ALABAMA,AL,Marshall County,Kate D Smith DAR Elem Sch,215,223,0,0,0,...,2,0,2,0.6,2,4,2,0,2,0
22,22,ALABAMA,AL,Marshall County,Douglas Middle Sch,250,218,0,0,0,...,66,0,94,22.6,1,4,53,13,17,2
23,23,ALABAMA,AL,Marshall County,Asbury Elem Sch,237,259,0,0,0,...,0,0,4,0.4,4,4,0,0,0,0
24,24,ALABAMA,AL,Hoover City,Trace Crossings Elem Sch,334,238,0,0,0,...,0,0,2,0.2,5,5,0,0,0,0
25,1400,ALASKA,AK,Lower Kuskokwim School District,Joann A. Alexie Memorial School,50,65,No,0,0,...,0,0,2,0.2,5,4,0,0,0,0
26,1401,ALASKA,AK,Lower Kuskokwim School District,Gladys Jung Elementary,175,184,0,0,0,...,2,0,13,1.7,1,4,2,0,0,0
27,1402,ALASKA,AK,Lower Kuskokwim School District,Bethel Regional High School,306,234,Yes,6,50,...,0,0,41,4.1,1,2,0,0,0,0
28,1403,ALASKA,AK,Lower Kuskokwim School District,Chaputnguak School,86,74,No,0,0,...,0,0,2,0.2,5,4,0,0,0,0
29,1404,ALASKA,AK,Lower Kuskokwim School District,Chief Paul Memorial School,119,106,No,0,0,...,0,0,4,0.4,4,4,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,93783,WISCONSIN,WI,Wisconsin Department of Health Services,Northern Wisconsin Center,5,2,No,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1246,93784,WISCONSIN,WI,Wisconsin Department of Health Services,Winnebago Mental Health Institution,58,32,No,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1247,93785,WISCONSIN,WI,Wisconsin Department of Health Services,Wisconsin Resource Center,4,2,No,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1248,93786,WISCONSIN,WI,Wisconsin Department of Health Services,Central Wisconsin Center,10,6,No,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1249,93787,WISCONSIN,WI,Wisconsin Department of Health Services,Mendota Mental Health Institution,29,0,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1250,95995,WYOMING,WY,Normative Services - Administration Office,Normative Services,37,25,No,0,0,...,0,0,0,0.0,1,4,0,0,0,0
1251,95996,WYOMING,WY,Red Top Meadows - Administration Office,Red Top Meadows,9,0,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1252,95997,WYOMING,WY,Northwest Wyoming BOCES,Big Horn Basin Children's Center,11,2,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1253,95998,WYOMING,WY,Albany County School District #1,Laramie High School,366,333,Yes,20,91,...,0,0,43,4.3,1,3,0,0,0,0
1254,95999,WYOMING,WY,Albany County School District #1,Laramie Junior High School,464,413,No,0,0,...,0,8,59,8.3,1,4,0,0,0,0
1255,96000,WYOMING,WY,Albany County School District #1,Rock River High School,16,19,Yes,1,4,...,0,0,0,0.0,1,3,0,0,0,0
1256,96001,WYOMING,WY,Albany County School District #1,Indian Paintbrush Elementary,198,159,0,0,0,...,0,0,0,0.0,1,4,0,0,0,0
1257,96002,WYOMING,WY,Albany County School District #1,Beitel Elementary,159,122,0,0,0,...,0,0,0,0.0,1,4,0,0,0,0
1258,96003,WYOMING,WY,Albany County School District #1,Spring Creek Elementary,160,156,0,0,0,...,0,0,0,0.0,1,4,0,0,0,0
1259,96004,WYOMING,WY,Albany County School District #1,Centennial Elementary,5,8,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1260,96005,WYOMING,WY,Albany County School District #1,Harmony Elementary,16,8,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1261,96006,WYOMING,WY,Albany County School District #1,Velma Linford Elementary,225,202,0,0,0,...,0,2,8,1.4,1,4,0,0,0,0
1262,96007,WYOMING,WY,Albany County School District #1,Rock River Junior High School,9,8,0,0,0,...,0,0,0,0.0,1,4,0,0,0,0
1263,96008,WYOMING,WY,Albany County School District #1,Slade Elementary,150,159,0,0,0,...,0,0,6,0.6,2,4,0,0,0,0
1264,96009,WYOMING,WY,Albany County School District #1,Valley View Elementary,5,2,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1265,96010,WYOMING,WY,Albany County School District #1,Whiting High School,22,41,No,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1266,96011,WYOMING,WY,Albany County School District #1,Snowy Range Academy,85,100,No,0,0,...,0,0,0,0.0,1,4,0,0,0,0
1267,96012,WYOMING,WY,Albany County School District #1,Rock River Elementary,16,13,0,0,0,...,0,0,0,0.0,1,3,0,0,0,0
1268,96013,WYOMING,WY,Albany County School District #1,UW Laboratory School,145,129,No,0,0,...,0,0,0,0.0,1,4,0,0,0,0
1269,96014,WYOMING,WY,Albany County School District #1,Laramie Montessori Charter School,39,40,0,0,0,...,0,0,6,0.6,2,4,0,0,0,0
1270,96015,WYOMING,WY,Albany County School District #1,Notch Peak Elementary,0,2,0,0,0,...,0,0,0,0.0,1,2,0,0,0,0
1271,96016,WYOMING,WY,Fremont County School District #38,Arapahoe Elementary,198,219,0,0,0,...,2,0,13,1.7,1,3,0,2,0,0
1272,96017,WYOMING,WY,Fremont County School District #38,Arapaho Charter High School,14,16,No,0,0,...,0,0,2,0.2,5,4,0,0,0,0
1273,96018,WYOMING,WY,Carbon County School District #1,Rawlins High School,237,208,No,0,0,...,0,0,24,3.2,1,4,0,0,0,0
1274,96019,WYOMING,WY,Carbon County School District #1,Rawlins Middle School,189,177,0,0,0,...,0,2,37,4.3,1,4,0,0,0,0

In [125]:
school_layout_new.keys()

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'SCH_ENR_AS',
       'SCH_ENR_BL', 'SCH_ENR_HP', 'SCH_ENR_WH', 'SCH_ENR_TR', 'SCH_ENR_HI',
       'SCH_ENR_AM', 'TOT_ENR', 'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH',
       'VAL_BL', 'VAL_HP', 'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE',
       'RACE_SCORE', 'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES',
       'AP_SCORE', 'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE',
       'TOT_ARR', 'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES',
       'OFFENSES_SCORE', 'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE',
       'DISABLE_MALE', 'DISABLE_FEMALE'],
      dtype='object')

In [126]:
df2 = pd.melt(school_layout_new, id_vars=['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F','TOT_ENR', 'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH',
       'VAL_BL', 'VAL_HP', 'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE',
       'RACE_SCORE', 'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES',
       'AP_SCORE', 'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE',
       'TOT_ARR', 'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES',
       'OFFENSES_SCORE', 'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE',
       'DISABLE_MALE', 'DISABLE_FEMALE'],
                  var_name="Race", value_name="Value")

In [127]:
print(df2.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'TOT_ENR_M', 'TOT_ENR_F', 'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
       'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
       'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
       'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
       'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
       'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
       'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
       'DISABLE_FEMALE', 'Race', 'Value'],
      dtype='object')

In [128]:
df2 = pd.melt(df2, id_vars=['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_APENR_IND', 'SCH_APCOURSES',
       'TOT_APENR_M', 'TOT_APENR_F', 'TOT_SATACT_M', 'TOT_SATACT_F',
       'TOT_HBREPORTED_SEX_M', 'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M',
       'TOT_HBREPORTED_DIS_F', 'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
       'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
       'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
       'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
       'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
       'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
       'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
       'DISABLE_FEMALE', 'Race', 'Value'],
              var_name="Gender", value_name="GenderValue")

In [129]:
print(df2.keys())

Index(['Unnamed: 0', 'LEA_STATE_NAME', 'LEA_STATE', 'LEA_NAME', 'SCH_NAME',
       'SCH_APENR_IND', 'SCH_APCOURSES', 'TOT_APENR_M', 'TOT_APENR_F',
       'TOT_SATACT_M', 'TOT_SATACT_F', 'TOT_HBREPORTED_SEX_M',
       'TOT_HBREPORTED_SEX_F', 'TOT_HBREPORTED_DIS_M', 'TOT_HBREPORTED_DIS_F',
       'TOT_HBREPORTED_RAC_M', 'TOT_HBREPORTED_RAC_F',
       'TOT_HBDISCIPLINED_SEX_M', 'TOT_HBDISCIPLINED_SEX_F',
       'TOT_HBDISCIPLINED_RAC_M', 'TOT_HBDISCIPLINED_RAC_F',
       'TOT_HBDISCIPLINED_DIS_M', 'TOT_HBDISCIPLINED_DIS_F',
       'TOT_DISCWODIS_ISS_M', 'TOT_DISCWODIS_ISS_F', 'TOT_DISCWDIS_ISS_IDEA_M',
       'TOT_DISCWDIS_ISS_IDEA_F', 'TOT_DISCWODIS_ARR_M', 'TOT_DISCWODIS_ARR_F',
       'TOT_DISCWDIS_ARR_IDEA_M', 'TOT_DISCWDIS_ARR_IDEA_F',
       'TOT_DISCWODIS_EXPWE_M', 'TOT_DISCWODIS_EXPWE_F',
       'TOT_DISCWODIS_EXPWOE_M', 'TOT_DISCWODIS_EXPWOE_F',
       'TOT_DISCWDIS_EXPWOE_IDEA_M', 'TOT_DISCWDIS_EXPWE_IDEA_M',
       'TOT_DISCWDIS_EXPWE_IDEA_F', 'TOT_DISCWDIS_EXPWOE_IDEA_F',
       'TOT_DISCWDIS_EXPZT_IDEA_M', 'TOT_DISCWDIS_EXPZT_IDEA_F', 'TOT_ENR',
       'AVG_ENR', 'TOT_SATACT', 'VAL_SAT', 'VAL_WH', 'VAL_BL', 'VAL_HP',
       'VAL_TR', 'VAL_HI', 'VAL_AS', 'VAL_AM', 'VAL_RACE', 'RACE_SCORE',
       'VAL_GENDER', 'GENDER_SCORE', 'VAL_AP_COURSES', 'AP_SCORE',
       'VAL_SATACT_COURSES', 'SATACT_SCORE', 'COURSES_SCORE', 'TOT_ARR',
       'TOT_EXP', 'TOT_HARR', 'TOT_SUSP', 'VAL_OFFENSES', 'OFFENSES_SCORE',
       'SCHOOL_SCORE', 'ABLE_MALE', 'ABLE_FEMALE', 'DISABLE_MALE',
       'DISABLE_FEMALE', 'Race', 'Value', 'Gender', 'GenderValue'],
      dtype='object')

In [130]:
df2.Race.unique()

array(['SCH_ENR_AS', 'SCH_ENR_BL', 'SCH_ENR_HP', 'SCH_ENR_WH',
       'SCH_ENR_TR', 'SCH_ENR_HI', 'SCH_ENR_AM'], dtype=object)

In [131]:
df2.Gender.unique()

array(['TOT_ENR_M', 'TOT_ENR_F'], dtype=object)

In [132]:
df2.to_csv("all_states_racegender.csv")

In [133]:
df2.count()

Unnamed: 0                 17850
LEA_STATE_NAME             17850
LEA_STATE                  17850
LEA_NAME                   17850
SCH_NAME                   17850
SCH_APENR_IND              17850
SCH_APCOURSES              17850
TOT_APENR_M                17850
TOT_APENR_F                17850
TOT_SATACT_M               17850
TOT_SATACT_F               17850
TOT_HBREPORTED_SEX_M       17850
TOT_HBREPORTED_SEX_F       17850
TOT_HBREPORTED_DIS_M       17850
TOT_HBREPORTED_DIS_F       17850
TOT_HBREPORTED_RAC_M       17850
TOT_HBREPORTED_RAC_F       17850
TOT_HBDISCIPLINED_SEX_M    17850
TOT_HBDISCIPLINED_SEX_F    17850
TOT_HBDISCIPLINED_RAC_M    17850
TOT_HBDISCIPLINED_RAC_F    17850
TOT_HBDISCIPLINED_DIS_M    17850
TOT_HBDISCIPLINED_DIS_F    17850
TOT_DISCWODIS_ISS_M        17850
TOT_DISCWODIS_ISS_F        17850
TOT_DISCWDIS_ISS_IDEA_M    17850
TOT_DISCWDIS_ISS_IDEA_F    17850
TOT_DISCWODIS_ARR_M        17850
TOT_DISCWODIS_ARR_F        17850
TOT_DISCWDIS_ARR_IDEA_M    17850
                           ...
VAL_BL                     17850
VAL_HP                     17850
VAL_TR                     17850
VAL_HI                     17850
VAL_AS                     17850
VAL_AM                     17850
VAL_RACE                   17850
RACE_SCORE                 17850
VAL_GENDER                 17850
GENDER_SCORE               17850
VAL_AP_COURSES             17850
AP_SCORE                   17850
VAL_SATACT_COURSES         17850
SATACT_SCORE               17850
COURSES_SCORE              17850
TOT_ARR                    17850
TOT_EXP                    17850
TOT_HARR                   17850
TOT_SUSP                   17850
VAL_OFFENSES               17850
OFFENSES_SCORE             17850
SCHOOL_SCORE               17850
ABLE_MALE                  17850
ABLE_FEMALE                17850
DISABLE_MALE               17850
DISABLE_FEMALE             17850
Race                       17850
Value                      17850
Gender                     17850
GenderValue                17850
Length: 76, dtype: int64

### NOTE:
1. Calculate scores for race
2. calculate scores for gender  : absolute diff between tot_enr_m and tot_enr_F divide by tot-enr : do same scoring as race
3. Calculate score for AP : ap-tot/tot-enr . score is reverse of race score. do same thing for SAT/ACT and take avg of both for tot score.
4. Calculate score for offenses : 
Ignore IDEA columns. Calculate Tot by adding M+F. AT the end one column each for arrest(0.4), expulsion(0.2), suspension(0.1), harrasment(0.3). Multiply by weights (given) divide by enrollment and then assign scores similar to race. lower the better.
5. Total score : Avg of above
6. Change all negative value to 0s, drop schools with tot-enr = 0

7. List of final columns we need: 4 scores of race,gender,ap and offenses, 1 overall score, tot_enr, tot-enr-m, tot-enr-f, race, value of the race, all idefication columns(refer google doc),

```
var diffDimension = ndx.dimension(function(d){
		return Math.abs(d.TOT_ENR_M - d.TOT_ENR_F);
	});
var diffGroup = diffDimension.group().reduceCount();
subjectChart
    .width(768)
        .height(480)
        .x(d3.scale.linear().domain([50,100]))
        .brushOn(false)
        .dimension(diffDimension)
        .group(diffGroup); 
dc.renderAll();
dc.redrawAll();        
```